language: python
python:
 - "3.5"
before_script:
 - pip install python-coveralls
 - pip install coverage
 - pip install termcolor
script:
 - coverage run test_rpn.py
 - make
after_success:
 - coveralls
